databases:
  - name: backenddb
    plan: free
    databaseName: backend
    user: backend

services:
  - type: web
    plan: free
    name: backend
    runtime: python
    rootDir: backend
    buildCommand: './build.sh'
    startCommand: 'gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backenddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://your-frontend-domain.onrender.com